# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

parameters:
  - name: error
    displayName: Fail Pipeline
    type: string
    default: 'false'
    values:
      - 'false'
      - 'true'
pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- bash: |
    exit 1
  displayName: Fail build if partially successful
  condition: eq('${{ parameters.error }}', 'true')