# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

parameters:
  - name: env
    displayName: Environment
    type: string
    default: 'dev'
    values:
      - 'dev'
      - 'stg'
      - 'prod'
  - name: fullSynapseDeployment
    displayName: Force full deployment
    type: string
    default: 'false'
    values:
      - 'true'
      - 'false'
  - name: error
    displayName: Fail Pipeline
    type: string
    default: 'false'
    values:
      - 'false'
      - 'true'
pool:
  vmImage: ubuntu-latest

stages:

- template: stage-pipeline.yml
  parameters:
    environment: 'prod'
    runDeploy: eq('${{ parameters.env }}', 'prod')
- template: stage-pipeline.yml
  parameters:
    environment: 'stg'
    runDeploy: eq('${{ parameters.env }}', 'stg')
#steps:
#- checkout: self
#  fetchTags: true
#- script: |
#    echo Hello, world!
#    git status
#    git tag
#  displayName: 'Run a one-line script'
#
#- bash: |
#    exit 1
#  displayName: Fail build if partially successful
#  condition: eq('${{ parameters.error }}', 'true')

#- ${{ if eq(parameters.fullSynapseDeployment, 'false') }}:
#    - task: Bash@3
#      displayName: 'Remove unchanged notebooks and pipelines'
#      inputs:
#        targetType: 'filePath'
#        filePath: '_scripts/keepChangedNotebooksAndPipelines.sh'
#        arguments: ${{ parameters.env }}