parameters:
  - name: environment
    default: ''
  - name: runDeploy
    default: true
  - name: error
    default: false
stages:
- stage: 'Deploy_${{ parameters.environment }}'
  displayName: 'Deploy project in ${{ parameters.environment }}'
  variables:
    environment: ${{ parameters.environment }}
  condition: eq(${{ parameters.runDeploy }}, true)
  jobs:
    - deployment: deploy_synapse
      displayName: Deploy Synapse Workspace
      environment: '${{ parameters.environment }}'
      strategy:
        runOnce:
          deploy:
            steps:
            - script: |
                echo ${{ parameters.environment }}
              displayName: 'Hello world job'
            - bash: |
                exit 1
              displayName: Fail build if partially successful
              condition: eq('${{ parameters.error }}', 'true')
