name: cleaning tags

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        required: true
        default: 'prod'
        type: choice
        options:
          - prod
          - stg
  schedule: 
  - cron: '0 0 * * *'

jobs:
  cleaning:
    runs-on: ubuntu-latest
    steps:
      - name: Cleaning tags ${{ github.event.check_run.name }}
        run: |
          set -xo
          echo "Cleaning STG tags"
          tag_prefix='stg1'

          tag_numbers=$(git for-each-ref --sort=creatordate --format '%(refname) %(creatordate)' refs/tags |grep $tag_prefix | wc -l)
          echo "Number of tags [$tag_numbers] with prefix [$tag_prefix]"
          threadshold=50

          if [$tag_numbers -gt $threadshold ] 
          then
              echo "the number of tags [$tag_numbers] is greater than  $threadshold"
              tags_to_delete=$(($tag_numbers-$threadshold))
              echo "Tags to delete $tags_to_delete"
              git for-each-ref --sort=-creatordate --format '%(refname:short)' refs/tags|grep $tag_prefix |tail -n $tags_to_delete

              echo "Tags to keep"
              git for-each-ref --sort=creatordate --format '%(refname:short)' refs/tags|grep $tag_prefix |tail -n $threadshold
              # git for-each-ref --sort=-creatordate --format '%(refname:short)' refs/tags|grep stg |tail -n 2 |xargs git push origin --delete

          fi

  