name: move tags

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        required: true
        default: 'prod'
        type: choice
        options:
          - prod
          - stg
  check_run:
    types: [completed]

jobs:
  trace:
    runs-on: ubuntu-latest
    steps:
      - name: Print log ${{ github.event.check_run.name }}
        run: |
          echo "Any log works"
        env:
          EVENT: ${{ toJSON(github.event) }}
          GIT_CONTEXT: ${{ toJSON(github) }}
  tags:
    runs-on: ubuntu-latest
    if: |
      (github.sha == github.event.check_run.head_sha && github.event.check_run.conclusion == 'success' && 
      github.event.check_run.name == 'bamboox2go.bamboox-synapse (1) (Deploy project in stg Deploy Synapse Workspace)') ||
      github.event.check_run.name == 'bamboox2go.bamboox-synapse (1) (Deploy project in prod Deploy Synapse Workspace)'

    steps:
      # You have to check out your repo first.
      - uses: actions/checkout@v3
      - name: Test bump version and push tag
        id: tag_version_test
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ${{ github.event.check_run.name == 'bamboox2go.bamboox-synapse (1) (Deploy project in prod Deploy Synapse Workspace)' && 'v' || 'stg' }}
          dry_run: true
      - name: Set previous tag sha
        run: |
          git fetch --tags origin
          echo "GITHUB_PREV_TAG_SHA=$(git rev-list -n 1 $PREVIOUS_TAG)" >> $GITHUB_ENV
        env:
          PREVIOUS_TAG: ${{ steps.tag_version_test.outputs.previous_tag }}
          NUMBER: ${{ toJSON(github.event) }}
          GIT_CONTEXT: ${{ toJSON(github) }}
      - name: Bump version and push tag
        id: tag_version
        if: inputs.apply == 'true' &&  env.GITHUB_SHA_SHORT != github.event.check_run.head_sha
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ${{ github.event.check_run.name == 'bamboox2go.bamboox-synapse (1) (Deploy project in prod Deploy Synapse Workspace)' && 'v' || 'stg' }}
